/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
export namespace Components {
  /**
   * A simple button component for testing
   */
  interface MyButton {
    /**
     * Whether the button is disabled
     * @default false
     */
    disabled: boolean;
    /**
     * Button size
     * @default 'medium'
     */
    size: 'small' | 'medium' | 'large';
    /**
     * The button variant style
     * @default 'primary'
     */
    variant: 'primary' | 'secondary' | 'danger';
  }
}
export interface MyButtonCustomEvent<T> extends CustomEvent<T> {
  detail: T;
  target: HTMLMyButtonElement;
}
declare global {
  interface HTMLMyButtonElementEventMap {
    buttonClick: MouseEvent;
  }
  /**
   * A simple button component for testing
   */
  interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    addEventListener<K extends keyof HTMLMyButtonElementEventMap>(
      type: K,
      listener: (this: HTMLMyButtonElement, ev: MyButtonCustomEvent<HTMLMyButtonElementEventMap[K]>) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | AddEventListenerOptions,
    ): void;
    addEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | AddEventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLMyButtonElementEventMap>(
      type: K,
      listener: (this: HTMLMyButtonElement, ev: MyButtonCustomEvent<HTMLMyButtonElementEventMap[K]>) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof DocumentEventMap>(
      type: K,
      listener: (this: Document, ev: DocumentEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener<K extends keyof HTMLElementEventMap>(
      type: K,
      listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any,
      options?: boolean | EventListenerOptions,
    ): void;
    removeEventListener(
      type: string,
      listener: EventListenerOrEventListenerObject,
      options?: boolean | EventListenerOptions,
    ): void;
  }
  var HTMLMyButtonElement: {
    prototype: HTMLMyButtonElement;
    new (): HTMLMyButtonElement;
  };
  interface HTMLElementTagNameMap {
    'my-button': HTMLMyButtonElement;
  }
}
declare namespace LocalJSX {
  /**
   * A simple button component for testing
   */
  interface MyButton {
    /**
     * Whether the button is disabled
     * @default false
     */
    disabled?: boolean;
    /**
     * Emitted when the button is clicked
     */
    onButtonClick?: (event: MyButtonCustomEvent<MouseEvent>) => void;
    /**
     * Button size
     * @default 'medium'
     */
    size?: 'small' | 'medium' | 'large';
    /**
     * The button variant style
     * @default 'primary'
     */
    variant?: 'primary' | 'secondary' | 'danger';
  }
  interface IntrinsicElements {
    'my-button': MyButton;
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      /**
       * A simple button component for testing
       */
      'my-button': LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
    }
  }
}
