/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from '@stencil/core/runtime';
import { STENCIL_SIGNALS_SYMBOL, type ReadonlySignal } from '@stencil/core/signals';
export { STENCIL_SIGNALS_SYMBOL } from '@stencil/core/signals';
export namespace Components {
  interface MooPoo {}
  interface MyComponent {
    /**
     * The first name
     */
    first?: string;
    /**
     * The last name
     */
    last?: string;
    /**
     * The middle name
     */
    middle?: string;
  }
}
declare global {
  interface HTMLMooPooElement extends Components.MooPoo, HTMLStencilElement {}
  var HTMLMooPooElement: {
    prototype: HTMLMooPooElement;
    new (): HTMLMooPooElement;
  };
  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    readonly [STENCIL_SIGNALS_SYMBOL]?: ReadonlyMap<'first' | 'middle' | 'last', ReadonlySignal<unknown>>;
  }
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'moo-poo': HTMLMooPooElement;
    'my-component': HTMLMyComponentElement;
  }
}
declare namespace LocalJSX {
  interface MooPoo {}
  interface MyComponent {
    /**
     * The first name
     */
    first?: string;
    /**
     * The last name
     */
    last?: string;
    /**
     * The middle name
     */
    middle?: string;
  }

  interface MyComponentAttributes {
    first: string;
    middle: string;
    last: string;
  }

  interface IntrinsicElements {
    'moo-poo': MooPoo;
    'my-component': Omit<MyComponent, keyof MyComponentAttributes> & {
      [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K];
    } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & {
      [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K];
    };
  }
}
export { LocalJSX as JSX };
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'moo-poo': LocalJSX.IntrinsicElements['moo-poo'] & JSXBase.HTMLAttributes<HTMLMooPooElement>;
      'my-component': LocalJSX.IntrinsicElements['my-component'] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}
