/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * A component that throws in componentWillLoad when a required prop is missing.
     * Used to test that lifecycle hooks are called and errors propagate correctly.
     */
    interface LifecycleThrow {
        /**
          * Required label prop - throws if not provided
         */
        "label": string;
    }
    /**
     * A labelled badge that extends FormattedBase for its text formatting.
     * Demonstrates that vi.mock() intercepts imports used in inherited methods.
     */
    interface MyBadge {
        /**
          * The badge label — passed through this.format() before rendering
          * @default ''
         */
        "label": string;
    }
    /**
     * A simple button component for testing
     */
    interface MyButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * Button size
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The button variant style
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'danger';
    }
    /**
     * A card component with header, content, and footer slots
     */
    interface MyCard {
        /**
          * Card title
         */
        "cardTitle"?: string;
        /**
          * Card elevation (box-shadow depth)
          * @default 1
         */
        "elevation": 0 | 1 | 2 | 3;
        /**
          * Whether the card is interactive (adds hover effect)
          * @default false
         */
        "interactive": boolean;
    }
    /**
     * A label component that formats its value using the capitalize utility.
     * Used to demonstrate vi.mock() working with the stencilVitestPlugin.
     */
    interface MyLabel {
        /**
          * Raw text to display — run through `capitalize()` before rendering
          * @default ''
         */
        "value": string;
    }
    /**
     * Test component with scoped encapsulation (non-shadow) and slots
     * Stencil polyfills slot behavior and protects the component by monkey-patching
     * childNodes, children, firstChild, lastChild to only return lightDOM
     * Original accessors are moved to __childNodes, __children, etc.
     */
    interface NonShadowComponent {
    }
}
export interface MyButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyButtonElement;
}
declare global {
    /**
     * A component that throws in componentWillLoad when a required prop is missing.
     * Used to test that lifecycle hooks are called and errors propagate correctly.
     */
    interface HTMLLifecycleThrowElement extends Components.LifecycleThrow, HTMLStencilElement {
    }
    var HTMLLifecycleThrowElement: {
        prototype: HTMLLifecycleThrowElement;
        new (): HTMLLifecycleThrowElement;
    };
    /**
     * A labelled badge that extends FormattedBase for its text formatting.
     * Demonstrates that vi.mock() intercepts imports used in inherited methods.
     */
    interface HTMLMyBadgeElement extends Components.MyBadge, HTMLStencilElement {
    }
    var HTMLMyBadgeElement: {
        prototype: HTMLMyBadgeElement;
        new (): HTMLMyBadgeElement;
    };
    interface HTMLMyButtonElementEventMap {
        "buttonClick": MouseEvent;
    }
    /**
     * A simple button component for testing
     */
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLMyButtonElementEventMap>(type: K, listener: (this: HTMLMyButtonElement, ev: MyButtonCustomEvent<HTMLMyButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLMyButtonElementEventMap>(type: K, listener: (this: HTMLMyButtonElement, ev: MyButtonCustomEvent<HTMLMyButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    /**
     * A card component with header, content, and footer slots
     */
    interface HTMLMyCardElement extends Components.MyCard, HTMLStencilElement {
    }
    var HTMLMyCardElement: {
        prototype: HTMLMyCardElement;
        new (): HTMLMyCardElement;
    };
    /**
     * A label component that formats its value using the capitalize utility.
     * Used to demonstrate vi.mock() working with the stencilVitestPlugin.
     */
    interface HTMLMyLabelElement extends Components.MyLabel, HTMLStencilElement {
    }
    var HTMLMyLabelElement: {
        prototype: HTMLMyLabelElement;
        new (): HTMLMyLabelElement;
    };
    /**
     * Test component with scoped encapsulation (non-shadow) and slots
     * Stencil polyfills slot behavior and protects the component by monkey-patching
     * childNodes, children, firstChild, lastChild to only return lightDOM
     * Original accessors are moved to __childNodes, __children, etc.
     */
    interface HTMLNonShadowComponentElement extends Components.NonShadowComponent, HTMLStencilElement {
    }
    var HTMLNonShadowComponentElement: {
        prototype: HTMLNonShadowComponentElement;
        new (): HTMLNonShadowComponentElement;
    };
    interface HTMLElementTagNameMap {
        "lifecycle-throw": HTMLLifecycleThrowElement;
        "my-badge": HTMLMyBadgeElement;
        "my-button": HTMLMyButtonElement;
        "my-card": HTMLMyCardElement;
        "my-label": HTMLMyLabelElement;
        "non-shadow-component": HTMLNonShadowComponentElement;
    }
}
declare namespace LocalJSX {
    /**
     * A component that throws in componentWillLoad when a required prop is missing.
     * Used to test that lifecycle hooks are called and errors propagate correctly.
     */
    interface LifecycleThrow {
        /**
          * Required label prop - throws if not provided
         */
        "label"?: string;
    }
    /**
     * A labelled badge that extends FormattedBase for its text formatting.
     * Demonstrates that vi.mock() intercepts imports used in inherited methods.
     */
    interface MyBadge {
        /**
          * The badge label — passed through this.format() before rendering
          * @default ''
         */
        "label"?: string;
    }
    /**
     * A simple button component for testing
     */
    interface MyButton {
        /**
          * Whether the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Emitted when the button is clicked
         */
        "onButtonClick"?: (event: MyButtonCustomEvent<MouseEvent>) => void;
        /**
          * Button size
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The button variant style
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'danger';
    }
    /**
     * A card component with header, content, and footer slots
     */
    interface MyCard {
        /**
          * Card title
         */
        "cardTitle"?: string;
        /**
          * Card elevation (box-shadow depth)
          * @default 1
         */
        "elevation"?: 0 | 1 | 2 | 3;
        /**
          * Whether the card is interactive (adds hover effect)
          * @default false
         */
        "interactive"?: boolean;
    }
    /**
     * A label component that formats its value using the capitalize utility.
     * Used to demonstrate vi.mock() working with the stencilVitestPlugin.
     */
    interface MyLabel {
        /**
          * Raw text to display — run through `capitalize()` before rendering
          * @default ''
         */
        "value"?: string;
    }
    /**
     * Test component with scoped encapsulation (non-shadow) and slots
     * Stencil polyfills slot behavior and protects the component by monkey-patching
     * childNodes, children, firstChild, lastChild to only return lightDOM
     * Original accessors are moved to __childNodes, __children, etc.
     */
    interface NonShadowComponent {
    }

    interface LifecycleThrowAttributes {
        "label": string;
    }
    interface MyBadgeAttributes {
        "label": string;
    }
    interface MyButtonAttributes {
        "variant": 'primary' | 'secondary' | 'danger';
        "disabled": boolean;
        "size": 'small' | 'medium' | 'large';
    }
    interface MyCardAttributes {
        "cardTitle": string;
        "elevation": 0 | 1 | 2 | 3;
        "interactive": boolean;
    }
    interface MyLabelAttributes {
        "value": string;
    }

    interface IntrinsicElements {
        "lifecycle-throw": Omit<LifecycleThrow, keyof LifecycleThrowAttributes> & { [K in keyof LifecycleThrow & keyof LifecycleThrowAttributes]?: LifecycleThrow[K] } & { [K in keyof LifecycleThrow & keyof LifecycleThrowAttributes as `attr:${K}`]?: LifecycleThrowAttributes[K] } & { [K in keyof LifecycleThrow & keyof LifecycleThrowAttributes as `prop:${K}`]?: LifecycleThrow[K] };
        "my-badge": Omit<MyBadge, keyof MyBadgeAttributes> & { [K in keyof MyBadge & keyof MyBadgeAttributes]?: MyBadge[K] } & { [K in keyof MyBadge & keyof MyBadgeAttributes as `attr:${K}`]?: MyBadgeAttributes[K] } & { [K in keyof MyBadge & keyof MyBadgeAttributes as `prop:${K}`]?: MyBadge[K] };
        "my-button": Omit<MyButton, keyof MyButtonAttributes> & { [K in keyof MyButton & keyof MyButtonAttributes]?: MyButton[K] } & { [K in keyof MyButton & keyof MyButtonAttributes as `attr:${K}`]?: MyButtonAttributes[K] } & { [K in keyof MyButton & keyof MyButtonAttributes as `prop:${K}`]?: MyButton[K] };
        "my-card": Omit<MyCard, keyof MyCardAttributes> & { [K in keyof MyCard & keyof MyCardAttributes]?: MyCard[K] } & { [K in keyof MyCard & keyof MyCardAttributes as `attr:${K}`]?: MyCardAttributes[K] } & { [K in keyof MyCard & keyof MyCardAttributes as `prop:${K}`]?: MyCard[K] };
        "my-label": Omit<MyLabel, keyof MyLabelAttributes> & { [K in keyof MyLabel & keyof MyLabelAttributes]?: MyLabel[K] } & { [K in keyof MyLabel & keyof MyLabelAttributes as `attr:${K}`]?: MyLabelAttributes[K] } & { [K in keyof MyLabel & keyof MyLabelAttributes as `prop:${K}`]?: MyLabel[K] };
        "non-shadow-component": NonShadowComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * A component that throws in componentWillLoad when a required prop is missing.
             * Used to test that lifecycle hooks are called and errors propagate correctly.
             */
            "lifecycle-throw": LocalJSX.IntrinsicElements["lifecycle-throw"] & JSXBase.HTMLAttributes<HTMLLifecycleThrowElement>;
            /**
             * A labelled badge that extends FormattedBase for its text formatting.
             * Demonstrates that vi.mock() intercepts imports used in inherited methods.
             */
            "my-badge": LocalJSX.IntrinsicElements["my-badge"] & JSXBase.HTMLAttributes<HTMLMyBadgeElement>;
            /**
             * A simple button component for testing
             */
            "my-button": LocalJSX.IntrinsicElements["my-button"] & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            /**
             * A card component with header, content, and footer slots
             */
            "my-card": LocalJSX.IntrinsicElements["my-card"] & JSXBase.HTMLAttributes<HTMLMyCardElement>;
            /**
             * A label component that formats its value using the capitalize utility.
             * Used to demonstrate vi.mock() working with the stencilVitestPlugin.
             */
            "my-label": LocalJSX.IntrinsicElements["my-label"] & JSXBase.HTMLAttributes<HTMLMyLabelElement>;
            /**
             * Test component with scoped encapsulation (non-shadow) and slots
             * Stencil polyfills slot behavior and protects the component by monkey-patching
             * childNodes, children, firstChild, lastChild to only return lightDOM
             * Original accessors are moved to __childNodes, __children, etc.
             */
            "non-shadow-component": LocalJSX.IntrinsicElements["non-shadow-component"] & JSXBase.HTMLAttributes<HTMLNonShadowComponentElement>;
        }
    }
}
